[package]
name = "gtaurus"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "gtaurus_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
gtaurus_common = { path = "../../gtaurus_lib" }
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
tauri-plugin-store = "2"
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serialport = "4.8.1"
tungstenite = { version = "0.26", features = ["native-tls"] }
tokio = { version = "1.49.0", features = ["full"] }
reqwest = { version = "0.12", features = ["json", "multipart", "blocking"] }
serde_yaml = "0.9.34"
dirs = "6.0"
gcode = "0.6.1"
glam = "0.32.0"
regex = "1.12.3"
tokio-tungstenite = "0.26"
futures-util = "0.3.32"

[dev-dependencies]
mockall = "0.13.0"
tokio-test = "0.4.4"
