/*
 * @file surfacing.rs
 * @purpose Raster surfacing toolpath generation — produces G-code for a planar
 *          clearing operation across the full stock surface.
 */

/// Parameters forwarded from the frontend SurfacingWizard.
#[derive(Debug)]
pub struct SurfacingParams {
    pub width: f32,
    pub height: f32,
    pub total_depth: f32,
    pub depth_per_pass: f32,
    pub stepover: f32,
    pub angle_deg: f32,
    pub overtravel: f32,
    pub bidirectional: bool,
    pub safe_z: f32,
    pub feedrate: f32,
    pub plunge_rate: f32,
    pub spindle_rpm: u32,
    pub finish_pass: bool,
    pub use_inches: bool,
    /// Where the WCS zero point sits relative to the stock.
    /// One of: "front_left" | "front_right" | "back_left" | "back_right"
    pub origin: String,
}

/// Rotate a 2-D point by `angle_rad` around the origin.
fn rotate(x: f32, y: f32, angle_rad: f32) -> (f32, f32) {
    let c = angle_rad.cos();
    let s = angle_rad.sin();
    (c * x - s * y, s * x + c * y)
}

/// Liang-Barsky line clipping against an axis-aligned rectangle.
/// Returns `Some((start, end))` with the clipped endpoints, or `None` if the
/// segment lies entirely outside the clip rectangle.
fn clip_line(
    x0: f32, y0: f32, x1: f32, y1: f32,
    xmin: f32, xmax: f32, ymin: f32, ymax: f32,
) -> Option<((f32, f32), (f32, f32))> {
    let dx = x1 - x0;
    let dy = y1 - y0;
    let mut t0: f32 = 0.0;
    let mut t1: f32 = 1.0;

    for (p, q) in [(-dx, x0 - xmin), (dx, xmax - x0), (-dy, y0 - ymin), (dy, ymax - y0)] {
        if p == 0.0 {
            if q < 0.0 { return None; }
        } else {
            let r = q / p;
            if p < 0.0 {
                if r > t1 { return None; }
                if r > t0 { t0 = r; }
            } else {
                if r < t0 { return None; }
                if r < t1 { t1 = r; }
            }
        }
    }

    Some((
        (x0 + t0 * dx, y0 + t0 * dy),
        (x0 + t1 * dx, y0 + t1 * dy),
    ))
}

/// Core G-code generation — pure function with no I/O, so it is unit-testable.
pub fn build_surfacing_gcode(p: &SurfacingParams) -> Result<String, String> {
    if p.width <= 0.0 { return Err("width must be > 0".into()); }
    if p.height <= 0.0 { return Err("height must be > 0".into()); }
    if p.total_depth <= 0.0 { return Err("total_depth must be > 0".into()); }
    if p.depth_per_pass <= 0.0 { return Err("depth_per_pass must be > 0".into()); }
    if p.stepover <= 0.0 { return Err("stepover must be > 0".into()); }
    if p.feedrate <= 0.0 { return Err("feedrate must be > 0".into()); }
    if p.plunge_rate <= 0.0 { return Err("plunge_rate must be > 0".into()); }

    let unit_cmd = if p.use_inches { "G20" } else { "G21" };
    let num_passes = (p.total_depth / p.depth_per_pass).ceil() as u32;

    // Angle in radians — raster lines run parallel to the X-axis in rotated space.
    let angle_rad = p.angle_deg.to_radians();
    // Inverse rotation brings world coordinates into scan-line space.
    let inv_rad = -angle_rad;

    // Origin offset: where WCS zero sits relative to stock corner.
    let (x_off, y_off): (f32, f32) = match p.origin.as_str() {
        "front_right" => (-p.width, 0.0),
        "back_left"   => (0.0, -p.height),
        "back_right"  => (-p.width, -p.height),
        "center"      => (-p.width / 2.0, -p.height / 2.0),
        _             => (0.0, 0.0),  // "front_left" is the default
    };

    // Bounding box corners in world space, extended by overtravel.
    let corners_world = [
        (x_off - p.overtravel,           y_off - p.overtravel),
        (x_off + p.width + p.overtravel, y_off - p.overtravel),
        (x_off + p.width + p.overtravel, y_off + p.height + p.overtravel),
        (x_off - p.overtravel,           y_off + p.height + p.overtravel),
    ];

    // Rotate corners into scan space to find the swept extents.
    let rotated: Vec<(f32, f32)> = corners_world
        .iter()
        .map(|&(x, y)| rotate(x, y, inv_rad))
        .collect();

    let scan_x_min = rotated.iter().map(|&(x, _)| x).fold(f32::INFINITY, f32::min);
    let scan_x_max = rotated.iter().map(|&(x, _)| x).fold(f32::NEG_INFINITY, f32::max);
    let scan_y_min = rotated.iter().map(|&(_, y)| y).fold(f32::INFINITY, f32::min);
    let scan_y_max = rotated.iter().map(|&(_, y)| y).fold(f32::NEG_INFINITY, f32::max);

    // Clip rectangle in world space — tool must never leave this region.
    let clip_xmin = x_off - p.overtravel;
    let clip_xmax = x_off + p.width  + p.overtravel;
    let clip_ymin = y_off - p.overtravel;
    let clip_ymax = y_off + p.height + p.overtravel;

    let mut out = String::with_capacity(4096);

    // ── Preamble ────────────────────────────────────────────────────────────
    out.push_str(&format!("; Raster surfacing — generated by gTaurus\n"));
    out.push_str(&format!("; Stock: {:.3} x {:.3}  Depth: {:.3}  Passes: {}\n",
        p.width, p.height, p.total_depth, num_passes));
    out.push_str(&format!("; Step-over: {:.3}  Angle: {:.1}°  {}\n",
        p.stepover, p.angle_deg,
        if p.bidirectional { "Bidirectional" } else { "Unidirectional" }));
    out.push_str(&format!("{} G90 G94\n", unit_cmd));
    out.push_str(&format!("M3 S{}\n", p.spindle_rpm));
    out.push_str(&format!("G0 Z{:.4}\n", p.safe_z));

    // ── Passes ──────────────────────────────────────────────────────────────
    let total_passes = if p.finish_pass { num_passes + 1 } else { num_passes };

    for pass in 1..=total_passes {
        let cut_z = if p.finish_pass && pass == total_passes {
            -(p.total_depth + 0.05_f32)
        } else {
            -((pass as f32 * p.depth_per_pass).min(p.total_depth))
        };

        out.push_str(&format!("; Pass {} — Z{:.4}\n", pass, cut_z));

        let span = scan_y_max - scan_y_min;
        let num_lines = (span / p.stepover).floor() as u32;
        let start_offset = (span - (num_lines as f32 * p.stepover)) / 2.0;
        let mut y_scan = scan_y_min + start_offset;
        let mut line_idx: u32 = 0;

        while y_scan <= scan_y_max + 1e-4 {
            let forward = !p.bidirectional || (line_idx % 2 == 0);

            let (sx_scan, ex_scan) = if forward {
                (scan_x_min, scan_x_max)
            } else {
                (scan_x_max, scan_x_min)
            };

            // Rotate scan-space endpoints back to world space.
            let (sx, sy) = rotate(sx_scan, y_scan, angle_rad);
            let (ex, ey) = rotate(ex_scan, y_scan, angle_rad);

            // Clip the world-space segment to the stock + overtravel rectangle.
            // Lines that fall entirely outside are skipped.
            if let Some(((csx, csy), (cex, cey))) = clip_line(
                sx, sy, ex, ey,
                clip_xmin, clip_xmax, clip_ymin, clip_ymax,
            ) {
                out.push_str(&format!("G0 X{:.4} Y{:.4} Z{:.4}\n", csx, csy, p.safe_z));
                out.push_str(&format!("G1 Z{:.4} F{:.1}\n", cut_z, p.plunge_rate));
                out.push_str(&format!("G1 X{:.4} Y{:.4} F{:.1}\n", cex, cey, p.feedrate));

                if !p.bidirectional {
                    out.push_str(&format!("G0 Z{:.4}\n", p.safe_z));
                }
            }

            y_scan += p.stepover;
            line_idx += 1;
        }

        // Retract at end of pass
        out.push_str(&format!("G0 Z{:.4}\n", p.safe_z));
    }

    // ── Postamble ───────────────────────────────────────────────────────────
    out.push_str("M5\n");
    out.push_str("M30\n");

    Ok(out)
}

#[tauri::command]
pub fn generate_surfacing_toolpath(
    width: f32,
    height: f32,
    total_depth: f32,
    depth_per_pass: f32,
    stepover: f32,
    angle_deg: f32,
    overtravel: f32,
    bidirectional: bool,
    safe_z: f32,
    feedrate: f32,
    plunge_rate: f32,
    spindle_rpm: u32,
    finish_pass: bool,
    use_inches: bool,
    origin: String,
) -> Result<String, String> {
    let params = SurfacingParams {
        width,
        height,
        total_depth,
        depth_per_pass,
        stepover,
        angle_deg,
        overtravel,
        bidirectional,
        safe_z,
        feedrate,
        plunge_rate,
        spindle_rpm,
        finish_pass,
        use_inches,
        origin,
    };
    build_surfacing_gcode(&params)
}

// ── Unit Tests ───────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    fn default_params() -> SurfacingParams {
        SurfacingParams {
            width: 200.0,
            height: 150.0,
            total_depth: 1.0,
            depth_per_pass: 0.5,
            stepover: 10.0,
            angle_deg: 0.0,
            overtravel: 5.0,
            bidirectional: true,
            safe_z: 5.0,
            feedrate: 2000.0,
            plunge_rate: 500.0,
            spindle_rpm: 18000,
            finish_pass: false,
            use_inches: false,
            origin: "front_left".to_string(),
        }
    }

    #[test]
    fn test_gcode_contains_preamble() {
        let gcode = build_surfacing_gcode(&default_params()).unwrap();
        assert!(gcode.contains("G21 G90 G94"));
        assert!(gcode.contains("M3 S18000"));
        assert!(gcode.contains("G0 Z5.0000"));
    }

    #[test]
    fn test_gcode_contains_postamble() {
        let gcode = build_surfacing_gcode(&default_params()).unwrap();
        assert!(gcode.contains("M5"));
        assert!(gcode.contains("M30"));
    }

    #[test]
    fn test_correct_number_of_passes() {
        // total_depth=1.0, depth_per_pass=0.5 → 2 passes
        let gcode = build_surfacing_gcode(&default_params()).unwrap();
        assert!(gcode.contains("; Pass 1 — Z"));
        assert!(gcode.contains("; Pass 2 — Z"));
        assert!(!gcode.contains("; Pass 3 — Z"));
    }

    #[test]
    fn test_finish_pass_adds_extra_layer() {
        let mut p = default_params();
        p.finish_pass = true;
        let gcode = build_surfacing_gcode(&p).unwrap();
        // 2 roughing passes + 1 finish pass
        assert!(gcode.contains("; Pass 3 — Z"));
        assert!(!gcode.contains("; Pass 4 — Z"));
    }

    #[test]
    fn test_finish_pass_depth_is_total_plus_005() {
        let mut p = default_params();
        p.finish_pass = true;
        let gcode = build_surfacing_gcode(&p).unwrap();
        // total_depth=1.0 → finish z = -(1.0 + 0.05) = -1.05
        assert!(gcode.contains("Z-1.0500"), "Expected finish Z-1.0500 in:\n{}", &gcode[..200]);
    }

    #[test]
    fn test_inches_mode() {
        let mut p = default_params();
        p.use_inches = true;
        let gcode = build_surfacing_gcode(&p).unwrap();
        assert!(gcode.contains("G20 G90 G94"));
        assert!(!gcode.contains("G21"));
    }

    #[test]
    fn test_unidirectional_has_retract_between_lines() {
        let mut p = default_params();
        p.bidirectional = false;
        p.stepover = 50.0; // fewer lines for a simpler assertion
        let gcode = build_surfacing_gcode(&p).unwrap();
        // In unidirectional mode every cut line is followed by a Z retract before the next G0 move.
        // A retract "G0 Z5.0000" must appear more than once per pass (once at end of pass + once per cut line).
        let retract_count = gcode.matches("G0 Z5.0000").count();
        // 2 passes × (at least 4 lines per pass + 1 end-of-pass retract) > 2
        assert!(retract_count > 4, "Expected >4 retracts, got {}", retract_count);
    }

    #[test]
    fn test_validation_rejects_zero_width() {
        let mut p = default_params();
        p.width = 0.0;
        assert!(build_surfacing_gcode(&p).is_err());
    }

    #[test]
    fn test_validation_rejects_zero_depth() {
        let mut p = default_params();
        p.total_depth = 0.0;
        assert!(build_surfacing_gcode(&p).is_err());
    }

    #[test]
    fn test_validation_rejects_zero_stepover() {
        let mut p = default_params();
        p.stepover = 0.0;
        assert!(build_surfacing_gcode(&p).is_err());
    }

    #[test]
    fn test_45_degree_angle_produces_rotated_coordinates() {
        let mut p = default_params();
        p.angle_deg = 45.0;
        p.stepover = 50.0;
        let gcode = build_surfacing_gcode(&p).unwrap();
        // At 45° the X and Y coordinates of the first G0 move should not be axis-aligned integers
        // (they will have decimal components from rotation).
        let has_diagonal = gcode.lines().any(|line| {
            if !line.starts_with("G0 X") { return false; }
            let parts: Vec<&str> = line.split_whitespace().collect();
            parts.len() >= 2 && {
                let x_str = parts[1].trim_start_matches('X');
                let x_val: f32 = x_str.parse().unwrap_or(0.0);
                // A purely axis-aligned move at 0° would have x values like -5.0 or 205.0.
                // At 45°, the values will be non-trivial.
                x_val.fract().abs() > 0.01
            }
        });
        assert!(has_diagonal, "Expected diagonal (non-integer) X coordinates for 45° pass");
    }

    #[test]
    fn test_single_pass_when_depth_equals_per_pass() {
        let mut p = default_params();
        p.total_depth = 0.5;
        p.depth_per_pass = 0.5;
        let gcode = build_surfacing_gcode(&p).unwrap();
        assert!(gcode.contains("; Pass 1 — Z"));
        assert!(!gcode.contains("; Pass 2 — Z"));
    }
}
