import type { DescriptorEntry, SettingsEntry } from './aiCommandRouter.types';

export const SETTINGS_ENTRIES: SettingsEntry[] = [
  {
    title: 'Dashboard',
    tab: 'dashboard',
    section: 'dashboard',
    summary: 'Panel layout, order, default sizing, and dashboard organization.',
    keywords: ['dashboard', 'layout', 'panels', 'widgets'],
    score: 0,
  },
  {
    title: 'Widgets',
    tab: 'dashboard',
    section: 'widgets',
    summary: 'Dashboard widget visibility and arrangement controls.',
    keywords: ['widgets', 'dashboard widgets', 'panel visibility'],
    score: 0,
  },
  {
    title: 'Theme & UX',
    tab: 'ui',
    section: 'theme',
    summary: 'Theme presets, UI scale, and presentation preferences.',
    keywords: ['theme', 'ux', 'ui', 'scale', 'appearance'],
    score: 0,
  },
  {
    title: 'Top Menu',
    tab: 'ui',
    section: 'navigation',
    summary: 'Top-menu button visibility and shortcut access.',
    keywords: ['top menu', 'navigation', 'toolbar', 'buttons'],
    score: 0,
  },
  {
    title: 'Bed Visualizer',
    tab: 'ui',
    section: 'visualizer',
    summary: 'Visualizer display preferences, stock visibility, and mesh rendering.',
    keywords: ['visualizer', 'bed visualizer', 'mesh', 'stock'],
    score: 0,
  },
  {
    title: 'Stats Display',
    tab: 'ui',
    section: 'stats',
    summary: 'Machine statistics display and tracking presentation.',
    keywords: ['stats', 'statistics', 'oee', 'display'],
    score: 0,
  },
  {
    title: 'Camera',
    tab: 'ui',
    section: 'camera',
    summary: 'Camera stream URL, crosshair, and viewer behavior.',
    keywords: ['camera', 'stream', 'crowsnest'],
    score: 0,
  },
  {
    title: 'General',
    tab: 'machine',
    section: 'general',
    summary: 'Units, safe height, bed size, homing orientation, and machine basics.',
    keywords: ['general', 'units', 'safe height', 'bed size', 'homing', 'grbl'],
    score: 0,
  },
  {
    title: 'Connection',
    tab: 'machine',
    section: 'connection',
    summary: 'USB, Telnet, WebSocket bridge, ports, and polling configuration.',
    keywords: ['connection', 'serial', 'usb', 'telnet', 'websocket', 'bridge'],
    score: 0,
  },
  {
    title: 'File Manager',
    tab: 'machine',
    section: 'file-manager',
    summary: 'G-code storage path and file-management behavior.',
    keywords: ['file manager', 'files', 'gcode path', 'storage'],
    score: 0,
  },
  {
    title: 'Probe',
    tab: 'machine',
    section: 'probe',
    summary: 'Probe type, travel, retract, touch-plate geometry, and calibration.',
    keywords: ['probe', 'probing', 'touch plate', 'z offset', 'calibration'],
    score: 0,
  },
  {
    title: 'Spindle',
    tab: 'machine',
    section: 'spindle',
    summary: 'RPM limits, PWM scaling, acceleration, and spindle behavior.',
    keywords: ['spindle', 'rpm', 'pwm', 'speed', 'warmup'],
    score: 0,
  },
  {
    title: 'Macros',
    tab: 'machine',
    section: 'macros',
    summary: 'Saved G-code snippets and one-click macro execution.',
    keywords: ['macros', 'macro', 'snippets', 'tool change'],
    score: 0,
  },
  {
    title: 'Tool Changer',
    tab: 'machine',
    section: 'atc',
    summary: 'ATC positions, tool-change coordinates, and probe automation.',
    keywords: ['tool changer', 'atc', 'tool change'],
    score: 0,
  },
  {
    title: 'Rotary Config',
    tab: 'machine',
    section: 'rotary',
    summary: 'Rotary mode, steps per revolution, roller diameter, and config switching.',
    keywords: ['rotary', '4th axis', 'roller', 'chuck'],
    score: 0,
  },
  {
    title: 'AI Assistant',
    tab: 'machine',
    section: 'ai',
    summary: 'AI tier, API keys, model selection, and concise-mode behavior.',
    keywords: ['ai', 'assistant', 'llm', 'model', 'gemini', 'local'],
    score: 0,
  },
];

export const SHORTCUTS = [
  ['?', 'Send status query'],
  ['!', 'Feed hold'],
  ['~', 'Resume or cycle start'],
  ['Ctrl+X', 'Soft reset'],
  ['Up / Down', 'Cycle console history'],
  ['Ctrl+L', 'Clear console log'],
] as const;

export const SLASH_COMMANDS = [
  { name: 'commands', template: '/commands', summary: 'Show the available slash commands.' },
  { name: 'help', template: '/help ', summary: 'Search local help topics.' },
  { name: 'status', template: '/status', summary: 'Show live machine state and key FluidNC status commands.' },
  { name: 'settings', template: '/settings probe', summary: 'Search settings sections.' },
  { name: 'shortcuts', template: '/shortcuts', summary: 'Show keyboard shortcuts.' },
  { name: 'wizard', template: '/wizard carve', summary: 'Find a relevant wizard.' },
  { name: 'panel', template: '/panel probe', summary: 'Find a dashboard or top-menu panel.' },
  { name: 'open', template: '/open tool library', summary: 'Open a tool window, help topic, or settings section.' },
  { name: 'diagnose', template: '/diagnose probe fails after connect', summary: 'Run grounded AI troubleshooting.' },
  { name: 'gcode', template: '/gcode safe tool-change macro', summary: 'Generate or explain G-code with grounded context.' },
] as const;

export const WIZARD_ENTRIES: DescriptorEntry[] = [
  {
    title: 'Carve Wizard',
    summary: '11-step preflight for workholding, tooling, zeroing, safety, and start.',
    keywords: ['carve wizard', 'preflight', 'start carve', 'safety checks', 'zero method'],
    score: 0,
  },
  {
    title: 'Machine Setup Wizard',
    summary: 'Connection, dimensions, probe type, axis direction, and homing setup.',
    keywords: ['machine setup wizard', 'connection', 'axis direction', 'homing', 'dimensions'],
    score: 0,
  },
  {
    title: 'Surfacing Wizard',
    summary: 'Surfacing bit selection, pass parameters, preview, and G-code generation.',
    keywords: ['surfacing wizard', 'surfacing', 'spoilboard', 'toolpath preview'],
    score: 0,
  },
  {
    title: 'Job Resume & Recovery',
    summary: 'Recovery workflow for interrupted jobs with checkpoint and safe repositioning.',
    keywords: ['job resume', 'resume wizard', 'recovery', 'checkpoint'],
    score: 0,
  },
];

export const PANEL_ENTRIES: DescriptorEntry[] = [
  {
    title: 'Controls',
    summary: 'DRO, jogging, file controls, and execution controls in one workspace.',
    keywords: ['controls', 'dro', 'jogging', 'execution', 'simulation'],
    score: 0,
  },
  {
    title: 'G-code Console',
    summary: 'Direct command entry, controller responses, and command history.',
    keywords: ['console', 'gcode console', 'command history'],
    score: 0,
  },
  {
    title: 'Bed Visualizer',
    summary: '3D environment view with orientation, camera controls, and setup verification.',
    keywords: ['bed visualizer', '3d', 'visualizer'],
    score: 0,
  },
  {
    title: 'File Manager',
    summary: 'Browse, select, and manage G-code files used for carving or simulation.',
    keywords: ['file manager', 'files', 'gcode'],
    score: 0,
  },
  {
    title: 'Probe Panel',
    summary: 'Axis probing, touch-plate setup, and zero-set workflows.',
    keywords: ['probe panel', 'probing', 'touch plate', 'probe'],
    score: 0,
  },
  {
    title: 'Macros',
    summary: 'One-click execution of saved G-code routines.',
    keywords: ['macros', 'macro panel'],
    score: 0,
  },
  {
    title: 'Workpiece',
    summary: 'Current stock dimensions, offsets, and carve context.',
    keywords: ['workpiece', 'stock', 'offsets'],
    score: 0,
  },
  {
    title: 'Auto-Leveling',
    summary: 'Surface probing grid and compensation for uneven work surfaces.',
    keywords: ['autolevel', 'auto-leveling', 'mesh', 'surface mapping'],
    score: 0,
  },
  {
    title: 'Bit Library',
    summary: 'Tool definitions, active bit selection, and tool-usage tracking.',
    keywords: ['bit library', 'tool library', 'bits'],
    score: 0,
  },
  {
    title: 'Tool Changer',
    summary: 'Manual or assisted tool-change workflows tied to jobs.',
    keywords: ['tool changer', 'atc'],
    score: 0,
  },
  {
    title: 'Machine Stats',
    summary: 'OEE, utilization, and machine history reporting.',
    keywords: ['machine stats', 'stats', 'statistics', 'oee'],
    score: 0,
  },
  {
    title: 'AI Assistant',
    summary: 'Chat assistant for troubleshooting, explanations, and G-code generation.',
    keywords: ['ai assistant', 'assistant', 'ai'],
    score: 0,
  },
  {
    title: 'FluidNC Manager',
    summary: 'Controller-specific configuration and FluidNC maintenance actions.',
    keywords: ['fluidnc manager', 'fluidnc'],
    score: 0,
  },
  {
    title: 'Camera',
    summary: 'Camera stream viewer and alignment aid.',
    keywords: ['camera', 'viewer', 'stream'],
    score: 0,
  },
];
